XMC1400 XTREME Connectivity Kit
Infineon/getstarted-optiga-trust-m pull request #1
Opened 2020-04-09 16:52 UTC by oscarcreativeshop

Getting started documentation has been added along with wiki.

2020-04-14 07:42 UTC, ayushev requested changes
+, please:
remove getstarted-optiga-trust-m.wiki submodule
use standard trust-m repo, not trust-m-1
rename xmc1400-getstarted-optiga-trust-m to "xmc1400_xtreme_kit" (the same manner as the "xmc4800_iot_kit")
Don't updte the xmc4800 project, it should be left untouched
No build directories shall be submitted (Release/Debug)
Only one build configuration (preferably "Debug")

2020-04-14 07:42 UTC, ayushev commented on .gitmodules
> +[submodule "optiga-trust-m-1"]
i know you did this for the timebeing, so please move to the trust-m repo, not trust-m-1

2020-04-14 07:42 UTC, ayushev commented on README.md
> +## Quickstart XMC1400
I don't see a need to have two almost identical descriptions. Please update the existing one to reflect both options.

2020-04-14 07:42 UTC, ayushev commented on README.md
> +The guidance on how to compile and debug the setup you can find [here](https://github.com/oscarcreativeshop/getstarted-optiga-trust-m/wiki)
this should be infineon

2020-04-16 13:11 UTC, ayushev requested changes
Please remove .metadata folder
as before remove all DEBUG or RElease uild folders thay are not required for the build when you move the project

2020-04-16 16:48 UTC, oscarcreativeshop commented
I missed this one,
Done
thanks!
Oscar

From: Artem Yushev <notifications@github.com>
Reply-To: Infineon/getstarted-optiga-trust-m <reply@reply.github.com>
Date: Thursday, April 16, 2020 at 6:12 AM
To: Infineon/getstarted-optiga-trust-m <getstarted-optiga-trust-m@noreply.github.com>
Cc: oscarcreativeshop <oscarsandiaz@outlook.com>, Author <author@noreply.github.com>
Subject: Re: [Infineon/getstarted-optiga-trust-m] XMC1400 XTREME Connectivity Kit (#1)


@ayushev requested changes on this pull request.

Please remove .metadata folder
as before remove all DEBUG or RElease uild folders thay are not required for the build when you move the project

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/Infineon/getstarted-optiga-trust-m/pull/1#pullrequestreview-394616789>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AFHUYSANACGZJCYZLCEKMRDRM372NANCNFSM4ME363BQ>.

2020-05-07 16:50 UTC, merged